# Moments: the candidates, registered and written for submission

Settings + plane → the 13 moments (`models/moments_film_mlp.py`). Five candidates, each trained on
the split of `moments_task/01_moments.ipynb` (injected configs, seed 12: 60% train, 20% validation
for the epochs, 20% test), scored on the test configs and registered; then retrained on all injected
configs, registered with `_all`, loaded back from the registry and written as a submission:

| candidate | what |
|---|---|
| `mlp` | the MLP of `01_moments.ipynb` (the file handed in so far), retrained here |
| `mlp_physics` | the same + 4 physics inputs: n_plateau, z_from_end, n_e, dE_gain |
| `film_centroid_term` | FiLM Gaussian, loss + 1 × MSE of the four transverse centroids |
| `hybrid_film_mlp_physics` | FiLM Gaussian without the term; the four centroids from `mlp_physics` |
| `hybrid_film_avg_centroids` | the same, centroids averaged over `mlp_physics` and `film_centroid_term` |

In [1]:
import os
from pathlib import Path

if Path.cwd().name == "notebooks":
    os.chdir("..")

import copy
import shutil
import time
from types import SimpleNamespace

import numpy as np
import pandas as pd
import torch

import pallas_pipeline as pp
import pallas_score

OWNER = "m"
CASE = "moments"
MODEL_FILE = "models/moments_film_mlp.py"
FV_NAME, FV_VERSION = "m_moments_raw_fv", 1
SEED = 12
DEVICE = "cuda:1"
EPOCHS = 400
REGISTER = False

torch.set_num_threads(16)
project = pp.connect(pp.PROJECT)
fs = project.get_feature_store()
module = pp.load_model_file(MODEL_FILE)
TARGETS = module.targets
started = time.time()

/home/mlenivenko/miniconda3/envs/torch/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

2026-10-15 14:19:21,513 INFO: Initializing external client

2026-10-15 14:19:21,514 INFO: Base URL: https://aissai26.hops.live:443

2026-10-15 14:19:22,714 INFO: Python Engine initialized.

Logged in to project, explore it here https://aissai26.hops.live:443/p/2170

## 1. Rows and split

A feature view over `pallas_b_moments`, `particle_group == "all"`: config, plane, settings, charge,
the six means and the 21 covariance entries (FiLM needs the off-diagonal ones). Rows without a bunch
(`q_tot_pC = 0`) and non-injected configs are dropped; the widths are √ of the covariance diagonal.

In [2]:
COLUMNS = (["config", "plane_mm", "q_tot_pC"] + module.SETTINGS + [f"mean_{c}_um" for c in ["zeta", "y", "z"]]
           + ["mean_ux", "mean_uy", "mean_uz"] + [f"cov_{i}{j}" for i in range(6) for j in range(i, 6)])
fv = pp.get_feature_view(fs, FV_NAME, FV_VERSION)
if fv is None:
    fg = fs.get_feature_group("pallas_b_moments", version=1)
    query = fg.select([pp.fs_name(c) for c in COLUMNS]).filter(fg.particle_group == "all")
    fv = fs.create_feature_view(name=FV_NAME, version=FV_VERSION, query=query, training_helper_columns=["config"],
                                description="moments, group all: settings + plane_mm, charge, means, full covariance")
    print(f"created {FV_NAME} v{FV_VERSION}")
TD_VERSION = pp.prepare_statistics(fv)

rows = fv.query.read().rename(columns={pp.fs_name(c): c for c in COLUMNS})[COLUMNS]
rows = rows.rename(columns={f"mean_{c}_um": f"mean_{c}" for c in ["zeta", "y", "z"]})
for i, c in enumerate(module.COORDS):
    rows[f"sigma_{c}"] = np.sqrt(rows[f"cov_{i}{i}"])
b = fs.get_feature_group("pallas_campaign_b", version=1).select(["config", "injected"]).read()
rows = rows[(rows.q_tot_pC > 0) & rows.config.isin(b.config[b.injected])]
rows = rows.sort_values(["config", "plane_mm"]).reset_index(drop=True)

configs = np.sort(rows.config.unique())
order = np.random.default_rng(SEED).permutation(configs)
n_train, n_val = int(0.6 * len(configs)), int(0.2 * len(configs))
fold = {c: "train" for c in order[:n_train]} | {c: "val" for c in order[n_train:n_train + n_val]} | {c: "test" for c in order[n_train + n_val:]}
rows["fold"] = rows.config.map(fold)
train, val, test = (rows[rows.fold == f].reset_index(drop=True) for f in ["train", "val", "test"])
test_configs = [int(c) for c in order[n_train + n_val:]]
print(train.config.nunique(), "train,", val.config.nunique(), "validation,", test.config.nunique(), "test configs;",
      len(train), "/", len(val), "/", len(test), "rows")


def score(model, df):
    sub = pd.concat([df[["config", "plane_mm"]], model.predict(df)], axis=1)
    return pallas_score.score_submission(sub, df[["config", "plane_mm", "L_inj"] + TARGETS])

Finished: Reading data from Hopsworks, using Hopsworks Feature Query Service (1.74s)

Finished: Reading data from Hopsworks, using Hopsworks Feature Query Service (0.49s)
1729 train, 576 validation, 577 test configs; 34563 / 11515 / 11533 rows

## 2. Train on the split, score the test configs

About 40 minutes on one GPU, most of it the two FiLM ensembles.

In [3]:
parts = {"mlp": module.build_model("mlp", epochs=EPOCHS, device=DEVICE),
         "mlp_physics": module.build_model("mlp", use_physics=True, epochs=EPOCHS, device=DEVICE),
         "film": module.build_model("film", lambda_c=0.0, weighted=True, epochs=EPOCHS, device=DEVICE),
         "film_centroid_term": module.build_model("film", lambda_c=1.0, weighted=False, epochs=EPOCHS, device=DEVICE)}
for name, m in parts.items():
    print(name, flush=True)
    m.fit(train, val)
    print(f"--- {(time.time() - started) / 60:.1f} min", flush=True)


def candidates(parts):
    return {"mlp": parts["mlp"], "mlp_physics": parts["mlp_physics"], "film_centroid_term": parts["film_centroid_term"],
            "hybrid_film_mlp_physics": module.Hybrid(parts["film"], module.centroids, [parts["mlp_physics"]]),
            "hybrid_film_avg_centroids": module.Hybrid(parts["film"], module.centroids,
                                                       [parts["mlp_physics"], parts["film_centroid_term"]])}


models = candidates(parts)
table = pd.DataFrame({name: score(m, test) for name, m in models.items()}).T
table[TARGETS + ["mean"]].round(3)

mlp

  kept epoch 57, validation loss 0.1909

  kept epoch 54, validation loss 0.1910

  kept epoch 54, validation loss 0.1886

  kept epoch 57, validation loss 0.1887

  kept epoch 59, validation loss 0.1923

--- 3.9 min

mlp_physics

  kept epoch 56, validation loss 0.1821

  kept epoch 47, validation loss 0.1842

  kept epoch 54, validation loss 0.1800

  kept epoch 56, validation loss 0.1818

  kept epoch 45, validation loss 0.1835

--- 8.0 min

film

  kept epoch 313, validation loss 2.7893

  kept epoch 260, validation loss 2.7914

  kept epoch 140, validation loss 2.7980

  kept epoch 208, validation loss 2.7923

  kept epoch 254, validation loss 2.7895

--- 23.1 min

film_centroid_term

  kept epoch 78, validation loss 1.4866

  kept epoch 67, validation loss 1.4922

  kept epoch 63, validation loss 1.4814

  kept epoch 69, validation loss 1.4705

  kept epoch 69, validation loss 1.4781

--- 39.2 min

,mean_zeta,mean_y,mean_z,mean_ux,mean_uy,mean_uz,sigma_zeta,sigma_y,sigma_z,sigma_ux,sigma_uy,sigma_uz,q_tot_pC,mean
mlp,0.954,0.433,0.176,0.995,0.724,0.496,0.956,0.977,0.970,0.974,0.970,0.948,0.995,0.813
mlp_physics,0.964,0.441,0.190,0.996,0.746,0.523,0.949,0.976,0.966,0.966,0.963,0.947,0.997,0.817
film_centroid_term,0.955,0.430,0.149,0.997,0.756,0.521,0.939,0.983,0.976,0.975,0.975,0.946,0.998,0.815
hybrid_film_mlp_physics,0.985,0.441,0.190,0.999,0.746,0.523,0.968,0.985,0.978,0.987,0.978,0.951,1.000,0.825
hybrid_film_avg_centroids,0.985,0.444,0.180,0.999,0.758,0.530,0.968,0.985,0.978,0.987,0.978,0.951,1.000,0.826

## 3. Register the split models

Metrics `holdout_*` are on the 577 test configs (the validation configs only picked epochs).
Each bundle also carries `physics_formulas.py`, for the physics inputs.

In [4]:
DESCRIPTIONS = {
    "mlp": "MLP 5 nets, settings + plane (01_moments.ipynb)",
    "mlp_physics": "MLP 5 nets, settings + plane + n_plateau, z_from_end, n_e, dE_gain",
    "film_centroid_term": "FiLM Gaussian 5 nets, NLL + log-q MSE + 1 x transverse-centroid MSE",
    "hybrid_film_mlp_physics": "FiLM Gaussian 5 nets (NLL + log-q MSE) with the 4 transverse centroids from mlp_physics",
    "hybrid_film_avg_centroids": "FiLM Gaussian 5 nets with the 4 transverse centroids averaged over mlp_physics and film_centroid_term"}


def register(model, name, meta, metrics, description):
    bundle = pp.save_bundle(model, MODEL_FILE, meta, Path("team_models") / name)
    shutil.copy("physics_formulas.py", bundle / "physics_formulas.py")
    if not REGISTER:
        return None
    entry = pp.register_model(project, bundle, name, fv, TD_VERSION, metrics, description)
    print(f"registered {name} v{entry.version}", flush=True)
    return entry


metrics, metas = {}, {}
for name, m in models.items():
    metrics[name] = {"holdout_mean_r2": table.loc[name, "mean"],
                     **{f"holdout_r2_{pp.fs_name(t)}": table.loc[name, t] for t in TARGETS}}
    metas[name] = {"case": CASE, "inputs": module.SETTINGS + ["plane_mm"], "targets": TARGETS,
                   "feature_view": FV_NAME, "feature_view_version": FV_VERSION, "td_version": TD_VERSION,
                   "model_file": Path(MODEL_FILE).stem, "candidate": name, "split": "random 60/20/20 by config",
                   "seed": SEED, "test_configs": test_configs,
                   "epochs": {k: list(p.epochs) for k, p in parts.items()},
                   "holdout_scores": {k: float(v) for k, v in metrics[name].items()}}
    register(m, f"{OWNER}_{CASE}_{name}", metas[name], metrics[name],
             f"{CASE}: {DESCRIPTIONS[name]}; {FV_NAME} v{FV_VERSION}, test = 20% of injected configs (seed {SEED})")

  0%|          | 0/6 [00:00<?, ?it/s]

Creating model folder:   0%|          | 0/6 [00:00<?, ?it/s]

Creating model folder:  17%|█▋        | 1/6 [00:00<00:03,  1.33it/s]

Uploading model files:  17%|█▋        | 1/6 [00:00<00:03,  1.33it/s]

Uploading model files (0 dirs, 0 files):  17%|█▋        | 1/6 [00:00<00:03,  1.33it/s]

Moving model files from 'outputs/models/m_moments_mlp' to the model registry... This is the default behavior. Set keep_original_files=True to copy files instead.

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_mlp/model_meta.json: 0.000%|          | 0/7226 elapsed<00:00 remaining<?

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_mlp/model_meta.json: 100.000%|██████████| 7226/7226 elapsed<00:00 remaining<00:00

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_mlp/model_meta.json: 100.000%|██████████| 7226/7226 elapsed<00:00 remaining<00:00

Uploading model files (0 dirs, 1 files):  17%|█▋        | 1/6 [00:01<00:03,  1.33it/s]

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_mlp/physics_formulas.py: 0.000%|          | 0/20393 elapsed<00:00 remaining<?

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_mlp/physics_formulas.py: 100.000%|██████████| 20393/20393 elapsed<00:00 remaining<00:00

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_mlp/physics_formulas.py: 100.000%|██████████| 20393/20393 elapsed<00:00 remaining<00:00

Uploading model files (0 dirs, 2 files):  17%|█▋        | 1/6 [00:02<00:03,  1.33it/s]

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_mlp/pallas_score.py: 0.000%|          | 0/27702 elapsed<00:00 remaining<?

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_mlp/pallas_score.py: 100.000%|██████████| 27702/27702 elapsed<00:00 remaining<00:00

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_mlp/pallas_score.py: 100.000%|██████████| 27702/27702 elapsed<00:00 remaining<00:00

Uploading model files (0 dirs, 3 files):  17%|█▋        | 1/6 [00:03<00:03,  1.33it/s]

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_mlp/model.joblib: 0.000%|          | 0/4074288 elapsed<00:00 remaining<?

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_mlp/model.joblib: 100.000%|██████████| 4074288/4074288 elapsed<00:01 remaining<00:00

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_mlp/model.joblib: 100.000%|██████████| 4074288/4074288 elapsed<00:01 remaining<00:00

Uploading model files (0 dirs, 4 files):  17%|█▋        | 1/6 [00:04<00:03,  1.33it/s]

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_mlp/pallas_pipeline.py: 0.000%|          | 0/20406 elapsed<00:00 remaining<?

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_mlp/pallas_pipeline.py: 100.000%|██████████| 20406/20406 elapsed<00:00 remaining<00:00

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_mlp/pallas_pipeline.py: 100.000%|██████████| 20406/20406 elapsed<00:00 remaining<00:00

Uploading model files (0 dirs, 5 files):  17%|█▋        | 1/6 [00:05<00:03,  1.33it/s]

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_mlp/moments_film_mlp.py: 0.000%|          | 0/13078 elapsed<00:00 remaining<?

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_mlp/moments_film_mlp.py: 100.000%|██████████| 13078/13078 elapsed<00:00 remaining<00:00

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_mlp/moments_film_mlp.py: 100.000%|██████████| 13078/13078 elapsed<00:00 remaining<00:00

Uploading model files (0 dirs, 6 files):  17%|█▋        | 1/6 [00:06<00:03,  1.33it/s]

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_mlp/requirements.txt: 0.000%|          | 0/122 elapsed<00:00 remaining<?

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_mlp/requirements.txt: 100.000%|██████████| 122/122 elapsed<00:00 remaining<00:00

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_mlp/requirements.txt: 100.000%|██████████| 122/122 elapsed<00:00 remaining<00:00

Uploading model files (0 dirs, 7 files):  17%|█▋        | 1/6 [00:07<00:03,  1.33it/s]

Uploading model files (0 dirs, 7 files):  33%|███▎      | 2/6 [00:07<00:16,  4.08s/it]

Uploading input_example and model_schema:  33%|███▎      | 2/6 [00:07<00:16,  4.08s/it]

Uploading /tmp/tmpp_nt94m5/model_schema.json: 0.000%|          | 0/2455 elapsed<00:00 remaining<?

Uploading /tmp/tmpp_nt94m5/model_schema.json: 100.000%|██████████| 2455/2455 elapsed<00:00 remaining<00:00

Uploading /tmp/tmpp_nt94m5/model_schema.json: 100.000%|██████████| 2455/2455 elapsed<00:00 remaining<00:00

Uploading input_example and model_schema:  50%|█████     | 3/6 [00:07<00:07,  2.57s/it]

Registering model:  50%|█████     | 3/6 [00:07<00:07,  2.57s/it]

Registering model:  67%|██████▋   | 4/6 [00:08<00:03,  1.79s/it]

Waiting for model registration:  67%|██████▋   | 4/6 [00:08<00:03,  1.79s/it]

Waiting for model registration:  83%|████████▎ | 5/6 [00:13<00:03,  3.08s/it]

Model export complete:  83%|████████▎ | 5/6 [00:13<00:03,  3.08s/it]

Model export complete: 100%|██████████| 6/6 [00:13<00:00,  2.32s/it]

Model created, explore it at https://aissai26.hops.live:443/p/2170/models/m_moments_mlp/1
registered m_moments_mlp v1

  0%|          | 0/6 [00:00<?, ?it/s]

Creating model folder:   0%|          | 0/6 [00:00<?, ?it/s]

Creating model folder:  17%|█▋        | 1/6 [00:00<00:03,  1.40it/s]

Uploading model files:  17%|█▋        | 1/6 [00:00<00:03,  1.40it/s]

Uploading model files (0 dirs, 0 files):  17%|█▋        | 1/6 [00:00<00:03,  1.40it/s]

Moving model files from 'outputs/models/m_moments_mlp_physics' to the model registry... This is the default behavior. Set keep_original_files=True to copy files instead.

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_mlp_physics/model_meta.json: 0.000%|          | 0/7234 elapsed<00:00 remaining<?

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_mlp_physics/model_meta.json: 100.000%|██████████| 7234/7234 elapsed<00:00 remaining<00:00

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_mlp_physics/model_meta.json: 100.000%|██████████| 7234/7234 elapsed<00:00 remaining<00:00

Uploading model files (0 dirs, 1 files):  17%|█▋        | 1/6 [00:01<00:03,  1.40it/s]

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_mlp_physics/physics_formulas.py: 0.000%|          | 0/20393 elapsed<00:00 remaining<?

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_mlp_physics/physics_formulas.py: 100.000%|██████████| 20393/20393 elapsed<00:00 remaining<00:00

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_mlp_physics/physics_formulas.py: 100.000%|██████████| 20393/20393 elapsed<00:00 remaining<00:00

Uploading model files (0 dirs, 2 files):  17%|█▋        | 1/6 [00:02<00:03,  1.40it/s]

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_mlp_physics/pallas_score.py: 0.000%|          | 0/27702 elapsed<00:00 remaining<?

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_mlp_physics/pallas_score.py: 100.000%|██████████| 27702/27702 elapsed<00:00 remaining<00:00

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_mlp_physics/pallas_score.py: 100.000%|██████████| 27702/27702 elapsed<00:00 remaining<00:00

Uploading model files (0 dirs, 3 files):  17%|█▋        | 1/6 [00:03<00:03,  1.40it/s]

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_mlp_physics/model.joblib: 0.000%|          | 0/4094866 elapsed<00:00 remaining<?

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_mlp_physics/model.joblib: 100.000%|██████████| 4094866/4094866 elapsed<00:01 remaining<00:00

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_mlp_physics/model.joblib: 100.000%|██████████| 4094866/4094866 elapsed<00:01 remaining<00:00

Uploading model files (0 dirs, 4 files):  17%|█▋        | 1/6 [00:04<00:03,  1.40it/s]

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_mlp_physics/pallas_pipeline.py: 0.000%|          | 0/20406 elapsed<00:00 remaining<?

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_mlp_physics/pallas_pipeline.py: 100.000%|██████████| 20406/20406 elapsed<00:00 remaining<00:00

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_mlp_physics/pallas_pipeline.py: 100.000%|██████████| 20406/20406 elapsed<00:00 remaining<00:00

Uploading model files (0 dirs, 5 files):  17%|█▋        | 1/6 [00:05<00:03,  1.40it/s]

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_mlp_physics/moments_film_mlp.py: 0.000%|          | 0/13078 elapsed<00:00 remaining<?

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_mlp_physics/moments_film_mlp.py: 100.000%|██████████| 13078/13078 elapsed<00:00 remaining<00:00

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_mlp_physics/moments_film_mlp.py: 100.000%|██████████| 13078/13078 elapsed<00:00 remaining<00:00

Uploading model files (0 dirs, 6 files):  17%|█▋        | 1/6 [00:06<00:03,  1.40it/s]

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_mlp_physics/requirements.txt: 0.000%|          | 0/122 elapsed<00:00 remaining<?

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_mlp_physics/requirements.txt: 100.000%|██████████| 122/122 elapsed<00:00 remaining<00:00

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_mlp_physics/requirements.txt: 100.000%|██████████| 122/122 elapsed<00:00 remaining<00:00

Uploading model files (0 dirs, 7 files):  17%|█▋        | 1/6 [00:07<00:03,  1.40it/s]

Uploading model files (0 dirs, 7 files):  33%|███▎      | 2/6 [00:07<00:16,  4.14s/it]

Uploading input_example and model_schema:  33%|███▎      | 2/6 [00:07<00:16,  4.14s/it]

Uploading /tmp/tmp2htejmjg/model_schema.json: 0.000%|          | 0/2455 elapsed<00:00 remaining<?

Uploading /tmp/tmp2htejmjg/model_schema.json: 100.000%|██████████| 2455/2455 elapsed<00:00 remaining<00:00

Uploading /tmp/tmp2htejmjg/model_schema.json: 100.000%|██████████| 2455/2455 elapsed<00:00 remaining<00:00

Uploading input_example and model_schema:  50%|█████     | 3/6 [00:08<00:07,  2.60s/it]

Registering model:  50%|█████     | 3/6 [00:08<00:07,  2.60s/it]

Registering model:  67%|██████▋   | 4/6 [00:08<00:03,  1.80s/it]

Waiting for model registration:  67%|██████▋   | 4/6 [00:08<00:03,  1.80s/it]

Waiting for model registration:  83%|████████▎ | 5/6 [00:13<00:03,  3.09s/it]

Model export complete:  83%|████████▎ | 5/6 [00:13<00:03,  3.09s/it]

Model export complete: 100%|██████████| 6/6 [00:13<00:00,  2.33s/it]

Model created, explore it at https://aissai26.hops.live:443/p/2170/models/m_moments_mlp_physics/1
registered m_moments_mlp_physics v1

  0%|          | 0/6 [00:00<?, ?it/s]

Creating model folder:   0%|          | 0/6 [00:00<?, ?it/s]

Creating model folder:  17%|█▋        | 1/6 [00:00<00:04,  1.21it/s]

Uploading model files:  17%|█▋        | 1/6 [00:00<00:04,  1.21it/s]

Uploading model files (0 dirs, 0 files):  17%|█▋        | 1/6 [00:00<00:04,  1.21it/s]

Moving model files from 'outputs/models/m_moments_film_centroid_term' to the model registry... This is the default behavior. Set keep_original_files=True to copy files instead.

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_film_centroid_term/model_meta.json: 0.000%|          | 0/7243 elapsed<00:00 remaining<?

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_film_centroid_term/model_meta.json: 100.000%|██████████| 7243/7243 elapsed<00:00 remaining<00:00

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_film_centroid_term/model_meta.json: 100.000%|██████████| 7243/7243 elapsed<00:00 remaining<00:00

Uploading model files (0 dirs, 1 files):  17%|█▋        | 1/6 [00:01<00:04,  1.21it/s]

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_film_centroid_term/physics_formulas.py: 0.000%|          | 0/20393 elapsed<00:00 remaining<?

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_film_centroid_term/physics_formulas.py: 100.000%|██████████| 20393/20393 elapsed<00:00 remaining<00:00

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_film_centroid_term/physics_formulas.py: 100.000%|██████████| 20393/20393 elapsed<00:00 remaining<00:00

Uploading model files (0 dirs, 2 files):  17%|█▋        | 1/6 [00:02<00:04,  1.21it/s]

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_film_centroid_term/pallas_score.py: 0.000%|          | 0/27702 elapsed<00:00 remaining<?

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_film_centroid_term/pallas_score.py: 100.000%|██████████| 27702/27702 elapsed<00:00 remaining<00:00

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_film_centroid_term/pallas_score.py: 100.000%|██████████| 27702/27702 elapsed<00:00 remaining<00:00

Uploading model files (0 dirs, 3 files):  17%|█▋        | 1/6 [00:03<00:04,  1.21it/s]

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_film_centroid_term/model.joblib: 0.000%|          | 0/4424770 elapsed<00:00 remaining<?

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_film_centroid_term/model.joblib: 100.000%|██████████| 4424770/4424770 elapsed<00:01 remaining<00:00

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_film_centroid_term/model.joblib: 100.000%|██████████| 4424770/4424770 elapsed<00:01 remaining<00:00

Uploading model files (0 dirs, 4 files):  17%|█▋        | 1/6 [00:04<00:04,  1.21it/s]

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_film_centroid_term/pallas_pipeline.py: 0.000%|          | 0/20406 elapsed<00:00 remaining<?

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_film_centroid_term/pallas_pipeline.py: 100.000%|██████████| 20406/20406 elapsed<00:00 remaining<00:00

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_film_centroid_term/pallas_pipeline.py: 100.000%|██████████| 20406/20406 elapsed<00:00 remaining<00:00

Uploading model files (0 dirs, 5 files):  17%|█▋        | 1/6 [00:05<00:04,  1.21it/s]

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_film_centroid_term/moments_film_mlp.py: 0.000%|          | 0/13078 elapsed<00:00 remaining<?

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_film_centroid_term/moments_film_mlp.py: 100.000%|██████████| 13078/13078 elapsed<00:00 remaining<00:00

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_film_centroid_term/moments_film_mlp.py: 100.000%|██████████| 13078/13078 elapsed<00:00 remaining<00:00

Uploading model files (0 dirs, 6 files):  17%|█▋        | 1/6 [00:06<00:04,  1.21it/s]

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_film_centroid_term/requirements.txt: 0.000%|          | 0/122 elapsed<00:00 remaining<?

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_film_centroid_term/requirements.txt: 100.000%|██████████| 122/122 elapsed<00:00 remaining<00:00

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_film_centroid_term/requirements.txt: 100.000%|██████████| 122/122 elapsed<00:00 remaining<00:00

Uploading model files (0 dirs, 7 files):  17%|█▋        | 1/6 [00:07<00:04,  1.21it/s]

Uploading model files (0 dirs, 7 files):  33%|███▎      | 2/6 [00:07<00:15,  3.99s/it]

Uploading input_example and model_schema:  33%|███▎      | 2/6 [00:07<00:15,  3.99s/it]

Uploading /tmp/tmpf11g58wq/model_schema.json: 0.000%|          | 0/2455 elapsed<00:00 remaining<?

Uploading /tmp/tmpf11g58wq/model_schema.json: 100.000%|██████████| 2455/2455 elapsed<00:00 remaining<00:00

Uploading /tmp/tmpf11g58wq/model_schema.json: 100.000%|██████████| 2455/2455 elapsed<00:00 remaining<00:00

Uploading input_example and model_schema:  50%|█████     | 3/6 [00:07<00:07,  2.49s/it]

Registering model:  50%|█████     | 3/6 [00:07<00:07,  2.49s/it]

Registering model:  67%|██████▋   | 4/6 [00:08<00:03,  1.73s/it]

Waiting for model registration:  67%|██████▋   | 4/6 [00:08<00:03,  1.73s/it]

Waiting for model registration:  83%|████████▎ | 5/6 [00:13<00:03,  3.04s/it]

Model export complete:  83%|████████▎ | 5/6 [00:13<00:03,  3.04s/it]

Model export complete: 100%|██████████| 6/6 [00:13<00:00,  2.28s/it]

Model created, explore it at https://aissai26.hops.live:443/p/2170/models/m_moments_film_centroid_term/1
registered m_moments_film_centroid_term v1

  0%|          | 0/6 [00:00<?, ?it/s]

Creating model folder:   0%|          | 0/6 [00:00<?, ?it/s]

Creating model folder:  17%|█▋        | 1/6 [00:00<00:04,  1.04it/s]

Uploading model files:  17%|█▋        | 1/6 [00:00<00:04,  1.04it/s]

Uploading model files (0 dirs, 0 files):  17%|█▋        | 1/6 [00:00<00:04,  1.04it/s]

Moving model files from 'outputs/models/m_moments_hybrid_film_mlp_physics' to the model registry... This is the default behavior. Set keep_original_files=True to copy files instead.

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_hybrid_film_mlp_physics/model_meta.json: 0.000%|          | 0/7245 elapsed<00:00 remaining<?

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_hybrid_film_mlp_physics/model_meta.json: 100.000%|██████████| 7245/7245 elapsed<00:00 remaining<00:00

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_hybrid_film_mlp_physics/model_meta.json: 100.000%|██████████| 7245/7245 elapsed<00:00 remaining<00:00

Uploading model files (0 dirs, 1 files):  17%|█▋        | 1/6 [00:01<00:04,  1.04it/s]

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_hybrid_film_mlp_physics/physics_formulas.py: 0.000%|          | 0/20393 elapsed<00:00 remaining<?

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_hybrid_film_mlp_physics/physics_formulas.py: 100.000%|██████████| 20393/20393 elapsed<00:00 remaining<00:00

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_hybrid_film_mlp_physics/physics_formulas.py: 100.000%|██████████| 20393/20393 elapsed<00:00 remaining<00:00

Uploading model files (0 dirs, 2 files):  17%|█▋        | 1/6 [00:02<00:04,  1.04it/s]

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_hybrid_film_mlp_physics/pallas_score.py: 0.000%|          | 0/27702 elapsed<00:00 remaining<?

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_hybrid_film_mlp_physics/pallas_score.py: 100.000%|██████████| 27702/27702 elapsed<00:00 remaining<00:00

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_hybrid_film_mlp_physics/pallas_score.py: 100.000%|██████████| 27702/27702 elapsed<00:00 remaining<00:00

Uploading model files (0 dirs, 3 files):  17%|█▋        | 1/6 [00:03<00:04,  1.04it/s]

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_hybrid_film_mlp_physics/model.joblib: 0.000%|          | 0/8518768 elapsed<00:00 remaining<?

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_hybrid_film_mlp_physics/model.joblib: 100.000%|██████████| 8518768/8518768 elapsed<00:01 remaining<00:00

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_hybrid_film_mlp_physics/model.joblib: 100.000%|██████████| 8518768/8518768 elapsed<00:01 remaining<00:00

Uploading model files (0 dirs, 4 files):  17%|█▋        | 1/6 [00:05<00:04,  1.04it/s]

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_hybrid_film_mlp_physics/pallas_pipeline.py: 0.000%|          | 0/20406 elapsed<00:00 remaining<?

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_hybrid_film_mlp_physics/pallas_pipeline.py: 100.000%|██████████| 20406/20406 elapsed<00:00 remaining<00:00

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_hybrid_film_mlp_physics/pallas_pipeline.py: 100.000%|██████████| 20406/20406 elapsed<00:00 remaining<00:00

Uploading model files (0 dirs, 5 files):  17%|█▋        | 1/6 [00:05<00:04,  1.04it/s]

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_hybrid_film_mlp_physics/moments_film_mlp.py: 0.000%|          | 0/13078 elapsed<00:00 remaining<?

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_hybrid_film_mlp_physics/moments_film_mlp.py: 100.000%|██████████| 13078/13078 elapsed<00:00 remaining<00:00

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_hybrid_film_mlp_physics/moments_film_mlp.py: 100.000%|██████████| 13078/13078 elapsed<00:00 remaining<00:00

Uploading model files (0 dirs, 6 files):  17%|█▋        | 1/6 [00:06<00:04,  1.04it/s]

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_hybrid_film_mlp_physics/requirements.txt: 0.000%|          | 0/122 elapsed<00:00 remaining<?

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_hybrid_film_mlp_physics/requirements.txt: 100.000%|██████████| 122/122 elapsed<00:00 remaining<00:00

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_hybrid_film_mlp_physics/requirements.txt: 100.000%|██████████| 122/122 elapsed<00:00 remaining<00:00

Uploading model files (0 dirs, 7 files):  17%|█▋        | 1/6 [00:07<00:04,  1.04it/s]

Uploading model files (0 dirs, 7 files):  33%|███▎      | 2/6 [00:07<00:16,  4.17s/it]

Uploading input_example and model_schema:  33%|███▎      | 2/6 [00:07<00:16,  4.17s/it]

Uploading /tmp/tmpajv8mzix/model_schema.json: 0.000%|          | 0/2455 elapsed<00:00 remaining<?

Uploading /tmp/tmpajv8mzix/model_schema.json: 100.000%|██████████| 2455/2455 elapsed<00:00 remaining<00:00

Uploading /tmp/tmpajv8mzix/model_schema.json: 100.000%|██████████| 2455/2455 elapsed<00:00 remaining<00:00

Uploading input_example and model_schema:  50%|█████     | 3/6 [00:08<00:07,  2.63s/it]

Registering model:  50%|█████     | 3/6 [00:08<00:07,  2.63s/it]

Registering model:  67%|██████▋   | 4/6 [00:08<00:03,  1.83s/it]

Waiting for model registration:  67%|██████▋   | 4/6 [00:08<00:03,  1.83s/it]

Waiting for model registration:  83%|████████▎ | 5/6 [00:14<00:03,  3.11s/it]

Model export complete:  83%|████████▎ | 5/6 [00:14<00:03,  3.11s/it]

Model export complete: 100%|██████████| 6/6 [00:14<00:00,  2.36s/it]

Model created, explore it at https://aissai26.hops.live:443/p/2170/models/m_moments_hybrid_film_mlp_physics/1
registered m_moments_hybrid_film_mlp_physics v1

  0%|          | 0/6 [00:00<?, ?it/s]

Creating model folder:   0%|          | 0/6 [00:00<?, ?it/s]

Creating model folder:  17%|█▋        | 1/6 [00:00<00:03,  1.38it/s]

Uploading model files:  17%|█▋        | 1/6 [00:00<00:03,  1.38it/s]

Uploading model files (0 dirs, 0 files):  17%|█▋        | 1/6 [00:00<00:03,  1.38it/s]

Moving model files from 'outputs/models/m_moments_hybrid_film_avg_centroids' to the model registry... This is the default behavior. Set keep_original_files=True to copy files instead.

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_hybrid_film_avg_centroids/model_meta.json: 0.000%|          | 0/7248 elapsed<00:00 remaining<?

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_hybrid_film_avg_centroids/model_meta.json: 100.000%|██████████| 7248/7248 elapsed<00:00 remaining<00:00

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_hybrid_film_avg_centroids/model_meta.json: 100.000%|██████████| 7248/7248 elapsed<00:00 remaining<00:00

Uploading model files (0 dirs, 1 files):  17%|█▋        | 1/6 [00:01<00:03,  1.38it/s]

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_hybrid_film_avg_centroids/physics_formulas.py: 0.000%|          | 0/20393 elapsed<00:00 remaining<?

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_hybrid_film_avg_centroids/physics_formulas.py: 100.000%|██████████| 20393/20393 elapsed<00:00 remaining<00:00

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_hybrid_film_avg_centroids/physics_formulas.py: 100.000%|██████████| 20393/20393 elapsed<00:00 remaining<00:00

Uploading model files (0 dirs, 2 files):  17%|█▋        | 1/6 [00:02<00:03,  1.38it/s]

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_hybrid_film_avg_centroids/pallas_score.py: 0.000%|          | 0/27702 elapsed<00:00 remaining<?

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_hybrid_film_avg_centroids/pallas_score.py: 100.000%|██████████| 27702/27702 elapsed<00:00 remaining<00:00

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_hybrid_film_avg_centroids/pallas_score.py: 100.000%|██████████| 27702/27702 elapsed<00:00 remaining<00:00

Uploading model files (0 dirs, 3 files):  17%|█▋        | 1/6 [00:03<00:03,  1.38it/s]

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_hybrid_film_avg_centroids/model.joblib: 0.000%|          | 0/12942301 elapsed<00:00 remaining<?

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_hybrid_film_avg_centroids/model.joblib: 18.981%|█▉        | 2456541/12942301 elapsed<00:00 remaining<00:03

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_hybrid_film_avg_centroids/model.joblib: 100.000%|██████████| 12942301/12942301 elapsed<00:01 remaining<00:00

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_hybrid_film_avg_centroids/model.joblib: 100.000%|██████████| 12942301/12942301 elapsed<00:01 remaining<00:00

Uploading model files (0 dirs, 4 files):  17%|█▋        | 1/6 [00:04<00:03,  1.38it/s]

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_hybrid_film_avg_centroids/pallas_pipeline.py: 0.000%|          | 0/20406 elapsed<00:00 remaining<?

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_hybrid_film_avg_centroids/pallas_pipeline.py: 100.000%|██████████| 20406/20406 elapsed<00:00 remaining<00:00

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_hybrid_film_avg_centroids/pallas_pipeline.py: 100.000%|██████████| 20406/20406 elapsed<00:00 remaining<00:00

Uploading model files (0 dirs, 5 files):  17%|█▋        | 1/6 [00:05<00:03,  1.38it/s]

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_hybrid_film_avg_centroids/moments_film_mlp.py: 0.000%|          | 0/13078 elapsed<00:00 remaining<?

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_hybrid_film_avg_centroids/moments_film_mlp.py: 100.000%|██████████| 13078/13078 elapsed<00:00 remaining<00:00

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_hybrid_film_avg_centroids/moments_film_mlp.py: 100.000%|██████████| 13078/13078 elapsed<00:00 remaining<00:00

Uploading model files (0 dirs, 6 files):  17%|█▋        | 1/6 [00:06<00:03,  1.38it/s]

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_hybrid_film_avg_centroids/requirements.txt: 0.000%|          | 0/122 elapsed<00:00 remaining<?

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_hybrid_film_avg_centroids/requirements.txt: 100.000%|██████████| 122/122 elapsed<00:00 remaining<00:00

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_hybrid_film_avg_centroids/requirements.txt: 100.000%|██████████| 122/122 elapsed<00:00 remaining<00:00

Uploading model files (0 dirs, 7 files):  17%|█▋        | 1/6 [00:07<00:03,  1.38it/s]

Uploading model files (0 dirs, 7 files):  33%|███▎      | 2/6 [00:07<00:16,  4.08s/it]

Uploading input_example and model_schema:  33%|███▎      | 2/6 [00:07<00:16,  4.08s/it]

Uploading /tmp/tmpgi7nx_jx/model_schema.json: 0.000%|          | 0/2455 elapsed<00:00 remaining<?

Uploading /tmp/tmpgi7nx_jx/model_schema.json: 100.000%|██████████| 2455/2455 elapsed<00:00 remaining<00:00

Uploading /tmp/tmpgi7nx_jx/model_schema.json: 100.000%|██████████| 2455/2455 elapsed<00:00 remaining<00:00

Uploading input_example and model_schema:  50%|█████     | 3/6 [00:07<00:07,  2.58s/it]

Registering model:  50%|█████     | 3/6 [00:07<00:07,  2.58s/it]

Registering model:  67%|██████▋   | 4/6 [00:08<00:03,  1.80s/it]

Waiting for model registration:  67%|██████▋   | 4/6 [00:08<00:03,  1.80s/it]

Waiting for model registration:  83%|████████▎ | 5/6 [00:14<00:03,  3.17s/it]

Model export complete:  83%|████████▎ | 5/6 [00:14<00:03,  3.17s/it]

Model export complete: 100%|██████████| 6/6 [00:14<00:00,  2.36s/it]

Model created, explore it at https://aissai26.hops.live:443/p/2170/models/m_moments_hybrid_film_avg_centroids/1
registered m_moments_hybrid_film_avg_centroids v1

## 4. Retrain on all injected configs, register

Same epochs as step 2, no validation, scalers kept. The metrics attached are step 2's.

In [5]:
parts_all = copy.deepcopy(parts)
for name, m in parts_all.items():
    m.refit(rows)
print(f"--- retrained on {rows.config.nunique()} configs, {(time.time() - started) / 60:.1f} min")
models_all = candidates(parts_all)
registered = {}
for name, m in models_all.items():
    NAME_ALL = f"{OWNER}_{CASE}_{name}_all"
    meta = {**metas[name], "split": "all", "trained_on": "every injected configuration of the view",
            "holdout_scores_from": f"{OWNER}_{CASE}_{name} (the same recipe on the split)"}
    registered[name] = register(m, NAME_ALL, meta, metrics[name],
                                f"{CASE}: {DESCRIPTIONS[name]}; retrained on all injected configs of {FV_NAME} "
                                f"v{FV_VERSION} with the epochs of {OWNER}_{CASE}_{name}, whose test metrics these are")

--- retrained on 2882 configs, 61.3 min

  0%|          | 0/6 [00:00<?, ?it/s]

Creating model folder:   0%|          | 0/6 [00:00<?, ?it/s]

Creating model folder:  17%|█▋        | 1/6 [00:00<00:04,  1.09it/s]

Uploading model files:  17%|█▋        | 1/6 [00:00<00:04,  1.09it/s]

Uploading model files (0 dirs, 0 files):  17%|█▋        | 1/6 [00:00<00:04,  1.09it/s]

Moving model files from 'outputs/models/m_moments_mlp_all' to the model registry... This is the default behavior. Set keep_original_files=True to copy files instead.

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_mlp_all/model_meta.json: 0.000%|          | 0/7337 elapsed<00:00 remaining<?

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_mlp_all/model_meta.json: 100.000%|██████████| 7337/7337 elapsed<00:00 remaining<00:00

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_mlp_all/model_meta.json: 100.000%|██████████| 7337/7337 elapsed<00:00 remaining<00:00

Uploading model files (0 dirs, 1 files):  17%|█▋        | 1/6 [00:01<00:04,  1.09it/s]

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_mlp_all/physics_formulas.py: 0.000%|          | 0/20393 elapsed<00:00 remaining<?

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_mlp_all/physics_formulas.py: 100.000%|██████████| 20393/20393 elapsed<00:00 remaining<00:00

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_mlp_all/physics_formulas.py: 100.000%|██████████| 20393/20393 elapsed<00:00 remaining<00:00

Uploading model files (0 dirs, 2 files):  17%|█▋        | 1/6 [00:02<00:04,  1.09it/s]

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_mlp_all/pallas_score.py: 0.000%|          | 0/27702 elapsed<00:00 remaining<?

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_mlp_all/pallas_score.py: 100.000%|██████████| 27702/27702 elapsed<00:00 remaining<00:00

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_mlp_all/pallas_score.py: 100.000%|██████████| 27702/27702 elapsed<00:00 remaining<00:00

Uploading model files (0 dirs, 3 files):  17%|█▋        | 1/6 [00:03<00:04,  1.09it/s]

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_mlp_all/model.joblib: 0.000%|          | 0/4074302 elapsed<00:00 remaining<?

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_mlp_all/model.joblib: 100.000%|██████████| 4074302/4074302 elapsed<00:01 remaining<00:00

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_mlp_all/model.joblib: 100.000%|██████████| 4074302/4074302 elapsed<00:01 remaining<00:00

Uploading model files (0 dirs, 4 files):  17%|█▋        | 1/6 [00:04<00:04,  1.09it/s]

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_mlp_all/pallas_pipeline.py: 0.000%|          | 0/20406 elapsed<00:00 remaining<?

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_mlp_all/pallas_pipeline.py: 100.000%|██████████| 20406/20406 elapsed<00:00 remaining<00:00

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_mlp_all/pallas_pipeline.py: 100.000%|██████████| 20406/20406 elapsed<00:00 remaining<00:00

Uploading model files (0 dirs, 5 files):  17%|█▋        | 1/6 [00:05<00:04,  1.09it/s]

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_mlp_all/moments_film_mlp.py: 0.000%|          | 0/13078 elapsed<00:00 remaining<?

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_mlp_all/moments_film_mlp.py: 100.000%|██████████| 13078/13078 elapsed<00:00 remaining<00:00

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_mlp_all/moments_film_mlp.py: 100.000%|██████████| 13078/13078 elapsed<00:00 remaining<00:00

Uploading model files (0 dirs, 6 files):  17%|█▋        | 1/6 [00:06<00:04,  1.09it/s]

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_mlp_all/requirements.txt: 0.000%|          | 0/122 elapsed<00:00 remaining<?

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_mlp_all/requirements.txt: 100.000%|██████████| 122/122 elapsed<00:00 remaining<00:00

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_mlp_all/requirements.txt: 100.000%|██████████| 122/122 elapsed<00:00 remaining<00:00

Uploading model files (0 dirs, 7 files):  17%|█▋        | 1/6 [00:07<00:04,  1.09it/s]

Uploading model files (0 dirs, 7 files):  33%|███▎      | 2/6 [00:07<00:17,  4.28s/it]

Uploading input_example and model_schema:  33%|███▎      | 2/6 [00:07<00:17,  4.28s/it]

Uploading /tmp/tmpu7bgc17l/model_schema.json: 0.000%|          | 0/2455 elapsed<00:00 remaining<?

Uploading /tmp/tmpu7bgc17l/model_schema.json: 100.000%|██████████| 2455/2455 elapsed<00:00 remaining<00:00

Uploading /tmp/tmpu7bgc17l/model_schema.json: 100.000%|██████████| 2455/2455 elapsed<00:00 remaining<00:00

Uploading input_example and model_schema:  50%|█████     | 3/6 [00:08<00:08,  2.69s/it]

Registering model:  50%|█████     | 3/6 [00:08<00:08,  2.69s/it]

Registering model:  67%|██████▋   | 4/6 [00:08<00:03,  1.85s/it]

Waiting for model registration:  67%|██████▋   | 4/6 [00:08<00:03,  1.85s/it]

Waiting for model registration:  83%|████████▎ | 5/6 [00:14<00:03,  3.12s/it]

Model export complete:  83%|████████▎ | 5/6 [00:14<00:03,  3.12s/it]

Model export complete: 100%|██████████| 6/6 [00:14<00:00,  2.38s/it]

Model created, explore it at https://aissai26.hops.live:443/p/2170/models/m_moments_mlp_all/1
registered m_moments_mlp_all v1

  0%|          | 0/6 [00:00<?, ?it/s]

Creating model folder:   0%|          | 0/6 [00:00<?, ?it/s]

Creating model folder:  17%|█▋        | 1/6 [00:00<00:04,  1.22it/s]

Uploading model files:  17%|█▋        | 1/6 [00:00<00:04,  1.22it/s]

Uploading model files (0 dirs, 0 files):  17%|█▋        | 1/6 [00:00<00:04,  1.22it/s]

Moving model files from 'outputs/models/m_moments_mlp_physics_all' to the model registry... This is the default behavior. Set keep_original_files=True to copy files instead.

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_mlp_physics_all/model_meta.json: 0.000%|          | 0/7353 elapsed<00:00 remaining<?

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_mlp_physics_all/model_meta.json: 100.000%|██████████| 7353/7353 elapsed<00:00 remaining<00:00

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_mlp_physics_all/model_meta.json: 100.000%|██████████| 7353/7353 elapsed<00:00 remaining<00:00

Uploading model files (0 dirs, 1 files):  17%|█▋        | 1/6 [00:01<00:04,  1.22it/s]

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_mlp_physics_all/physics_formulas.py: 0.000%|          | 0/20393 elapsed<00:00 remaining<?

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_mlp_physics_all/physics_formulas.py: 100.000%|██████████| 20393/20393 elapsed<00:00 remaining<00:00

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_mlp_physics_all/physics_formulas.py: 100.000%|██████████| 20393/20393 elapsed<00:00 remaining<00:00

Uploading model files (0 dirs, 2 files):  17%|█▋        | 1/6 [00:02<00:04,  1.22it/s]

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_mlp_physics_all/pallas_score.py: 0.000%|          | 0/27702 elapsed<00:00 remaining<?

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_mlp_physics_all/pallas_score.py: 100.000%|██████████| 27702/27702 elapsed<00:00 remaining<00:00

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_mlp_physics_all/pallas_score.py: 100.000%|██████████| 27702/27702 elapsed<00:00 remaining<00:00

Uploading model files (0 dirs, 3 files):  17%|█▋        | 1/6 [00:03<00:04,  1.22it/s]

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_mlp_physics_all/model.joblib: 0.000%|          | 0/4094858 elapsed<00:00 remaining<?

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_mlp_physics_all/model.joblib: 100.000%|██████████| 4094858/4094858 elapsed<00:01 remaining<00:00

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_mlp_physics_all/model.joblib: 100.000%|██████████| 4094858/4094858 elapsed<00:01 remaining<00:00

Uploading model files (0 dirs, 4 files):  17%|█▋        | 1/6 [00:04<00:04,  1.22it/s]

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_mlp_physics_all/pallas_pipeline.py: 0.000%|          | 0/20406 elapsed<00:00 remaining<?

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_mlp_physics_all/pallas_pipeline.py: 100.000%|██████████| 20406/20406 elapsed<00:00 remaining<00:00

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_mlp_physics_all/pallas_pipeline.py: 100.000%|██████████| 20406/20406 elapsed<00:00 remaining<00:00

Uploading model files (0 dirs, 5 files):  17%|█▋        | 1/6 [00:05<00:04,  1.22it/s]

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_mlp_physics_all/moments_film_mlp.py: 0.000%|          | 0/13078 elapsed<00:00 remaining<?

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_mlp_physics_all/moments_film_mlp.py: 100.000%|██████████| 13078/13078 elapsed<00:00 remaining<00:00

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_mlp_physics_all/moments_film_mlp.py: 100.000%|██████████| 13078/13078 elapsed<00:00 remaining<00:00

Uploading model files (0 dirs, 6 files):  17%|█▋        | 1/6 [00:06<00:04,  1.22it/s]

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_mlp_physics_all/requirements.txt: 0.000%|          | 0/122 elapsed<00:00 remaining<?

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_mlp_physics_all/requirements.txt: 100.000%|██████████| 122/122 elapsed<00:00 remaining<00:00

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_mlp_physics_all/requirements.txt: 100.000%|██████████| 122/122 elapsed<00:00 remaining<00:00

Uploading model files (0 dirs, 7 files):  17%|█▋        | 1/6 [00:07<00:04,  1.22it/s]

Uploading model files (0 dirs, 7 files):  33%|███▎      | 2/6 [00:07<00:15,  3.99s/it]

Uploading input_example and model_schema:  33%|███▎      | 2/6 [00:07<00:15,  3.99s/it]

Uploading /tmp/tmph43252pw/model_schema.json: 0.000%|          | 0/2455 elapsed<00:00 remaining<?

Uploading /tmp/tmph43252pw/model_schema.json: 100.000%|██████████| 2455/2455 elapsed<00:00 remaining<00:00

Uploading /tmp/tmph43252pw/model_schema.json: 100.000%|██████████| 2455/2455 elapsed<00:00 remaining<00:00

Uploading input_example and model_schema:  50%|█████     | 3/6 [00:07<00:07,  2.53s/it]

Registering model:  50%|█████     | 3/6 [00:07<00:07,  2.53s/it]

Registering model:  67%|██████▋   | 4/6 [00:08<00:03,  1.76s/it]

Waiting for model registration:  67%|██████▋   | 4/6 [00:08<00:03,  1.76s/it]

Waiting for model registration:  83%|████████▎ | 5/6 [00:13<00:03,  3.06s/it]

Model export complete:  83%|████████▎ | 5/6 [00:13<00:03,  3.06s/it]

Model export complete: 100%|██████████| 6/6 [00:13<00:00,  2.29s/it]

Model created, explore it at https://aissai26.hops.live:443/p/2170/models/m_moments_mlp_physics_all/1
registered m_moments_mlp_physics_all v1

  0%|          | 0/6 [00:00<?, ?it/s]

Creating model folder:   0%|          | 0/6 [00:00<?, ?it/s]

Creating model folder:  17%|█▋        | 1/6 [00:00<00:03,  1.35it/s]

Uploading model files:  17%|█▋        | 1/6 [00:00<00:03,  1.35it/s]

Uploading model files (0 dirs, 0 files):  17%|█▋        | 1/6 [00:00<00:03,  1.35it/s]

Moving model files from 'outputs/models/m_moments_film_centroid_term_all' to the model registry... This is the default behavior. Set keep_original_files=True to copy files instead.

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_film_centroid_term_all/model_meta.json: 0.000%|          | 0/7369 elapsed<00:00 remaining<?

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_film_centroid_term_all/model_meta.json: 100.000%|██████████| 7369/7369 elapsed<00:00 remaining<00:00

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_film_centroid_term_all/model_meta.json: 100.000%|██████████| 7369/7369 elapsed<00:00 remaining<00:00

Uploading model files (0 dirs, 1 files):  17%|█▋        | 1/6 [00:01<00:03,  1.35it/s]

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_film_centroid_term_all/physics_formulas.py: 0.000%|          | 0/20393 elapsed<00:00 remaining<?

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_film_centroid_term_all/physics_formulas.py: 100.000%|██████████| 20393/20393 elapsed<00:01 remaining<00:00

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_film_centroid_term_all/physics_formulas.py: 100.000%|██████████| 20393/20393 elapsed<00:01 remaining<00:00

Uploading model files (0 dirs, 2 files):  17%|█▋        | 1/6 [00:03<00:03,  1.35it/s]

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_film_centroid_term_all/pallas_score.py: 0.000%|          | 0/27702 elapsed<00:00 remaining<?

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_film_centroid_term_all/pallas_score.py: 100.000%|██████████| 27702/27702 elapsed<00:00 remaining<00:00

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_film_centroid_term_all/pallas_score.py: 100.000%|██████████| 27702/27702 elapsed<00:00 remaining<00:00

Uploading model files (0 dirs, 3 files):  17%|█▋        | 1/6 [00:03<00:03,  1.35it/s]

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_film_centroid_term_all/model.joblib: 0.000%|          | 0/4424774 elapsed<00:00 remaining<?

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_film_centroid_term_all/model.joblib: 100.000%|██████████| 4424774/4424774 elapsed<00:01 remaining<00:00

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_film_centroid_term_all/model.joblib: 100.000%|██████████| 4424774/4424774 elapsed<00:01 remaining<00:00

Uploading model files (0 dirs, 4 files):  17%|█▋        | 1/6 [00:05<00:03,  1.35it/s]

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_film_centroid_term_all/pallas_pipeline.py: 0.000%|          | 0/20406 elapsed<00:00 remaining<?

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_film_centroid_term_all/pallas_pipeline.py: 100.000%|██████████| 20406/20406 elapsed<00:00 remaining<00:00

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_film_centroid_term_all/pallas_pipeline.py: 100.000%|██████████| 20406/20406 elapsed<00:00 remaining<00:00

Uploading model files (0 dirs, 5 files):  17%|█▋        | 1/6 [00:05<00:03,  1.35it/s]

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_film_centroid_term_all/moments_film_mlp.py: 0.000%|          | 0/13078 elapsed<00:00 remaining<?

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_film_centroid_term_all/moments_film_mlp.py: 100.000%|██████████| 13078/13078 elapsed<00:00 remaining<00:00

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_film_centroid_term_all/moments_film_mlp.py: 100.000%|██████████| 13078/13078 elapsed<00:00 remaining<00:00

Uploading model files (0 dirs, 6 files):  17%|█▋        | 1/6 [00:06<00:03,  1.35it/s]

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_film_centroid_term_all/requirements.txt: 0.000%|          | 0/122 elapsed<00:00 remaining<?

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_film_centroid_term_all/requirements.txt: 100.000%|██████████| 122/122 elapsed<00:00 remaining<00:00

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_film_centroid_term_all/requirements.txt: 100.000%|██████████| 122/122 elapsed<00:00 remaining<00:00

Uploading model files (0 dirs, 7 files):  17%|█▋        | 1/6 [00:07<00:03,  1.35it/s]

Uploading model files (0 dirs, 7 files):  33%|███▎      | 2/6 [00:07<00:17,  4.39s/it]

Uploading input_example and model_schema:  33%|███▎      | 2/6 [00:07<00:17,  4.39s/it]

Uploading /tmp/tmpvkgg6p1z/model_schema.json: 0.000%|          | 0/2455 elapsed<00:00 remaining<?

Uploading /tmp/tmpvkgg6p1z/model_schema.json: 100.000%|██████████| 2455/2455 elapsed<00:01 remaining<00:00

Uploading /tmp/tmpvkgg6p1z/model_schema.json: 100.000%|██████████| 2455/2455 elapsed<00:01 remaining<00:00

Uploading input_example and model_schema:  50%|█████     | 3/6 [00:09<00:09,  3.04s/it]

Registering model:  50%|█████     | 3/6 [00:09<00:09,  3.04s/it]

Registering model:  67%|██████▋   | 4/6 [00:09<00:04,  2.06s/it]

Waiting for model registration:  67%|██████▋   | 4/6 [00:09<00:04,  2.06s/it]

Waiting for model registration:  83%|████████▎ | 5/6 [00:15<00:03,  3.25s/it]

Model export complete:  83%|████████▎ | 5/6 [00:15<00:03,  3.25s/it]

Model export complete: 100%|██████████| 6/6 [00:15<00:00,  2.51s/it]

Model created, explore it at https://aissai26.hops.live:443/p/2170/models/m_moments_film_centroid_term_all/1
registered m_moments_film_centroid_term_all v1

  0%|          | 0/6 [00:00<?, ?it/s]

Creating model folder:   0%|          | 0/6 [00:00<?, ?it/s]

Creating model folder:  17%|█▋        | 1/6 [00:00<00:03,  1.41it/s]

Uploading model files:  17%|█▋        | 1/6 [00:00<00:03,  1.41it/s]

Uploading model files (0 dirs, 0 files):  17%|█▋        | 1/6 [00:00<00:03,  1.41it/s]

Moving model files from 'outputs/models/m_moments_hybrid_film_mlp_physics_all' to the model registry... This is the default behavior. Set keep_original_files=True to copy files instead.

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_hybrid_film_mlp_physics_all/model_meta.json: 0.000%|          | 0/7376 elapsed<00:00 remaining<?

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_hybrid_film_mlp_physics_all/model_meta.json: 100.000%|██████████| 7376/7376 elapsed<00:00 remaining<00:00

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_hybrid_film_mlp_physics_all/model_meta.json: 100.000%|██████████| 7376/7376 elapsed<00:00 remaining<00:00

Uploading model files (0 dirs, 1 files):  17%|█▋        | 1/6 [00:01<00:03,  1.41it/s]

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_hybrid_film_mlp_physics_all/physics_formulas.py: 0.000%|          | 0/20393 elapsed<00:00 remaining<?

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_hybrid_film_mlp_physics_all/physics_formulas.py: 100.000%|██████████| 20393/20393 elapsed<00:00 remaining<00:00

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_hybrid_film_mlp_physics_all/physics_formulas.py: 100.000%|██████████| 20393/20393 elapsed<00:00 remaining<00:00

Uploading model files (0 dirs, 2 files):  17%|█▋        | 1/6 [00:02<00:03,  1.41it/s]

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_hybrid_film_mlp_physics_all/pallas_score.py: 0.000%|          | 0/27702 elapsed<00:00 remaining<?

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_hybrid_film_mlp_physics_all/pallas_score.py: 100.000%|██████████| 27702/27702 elapsed<00:00 remaining<00:00

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_hybrid_film_mlp_physics_all/pallas_score.py: 100.000%|██████████| 27702/27702 elapsed<00:00 remaining<00:00

Uploading model files (0 dirs, 3 files):  17%|█▋        | 1/6 [00:03<00:03,  1.41it/s]

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_hybrid_film_mlp_physics_all/model.joblib: 0.000%|          | 0/8518760 elapsed<00:00 remaining<?

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_hybrid_film_mlp_physics_all/model.joblib: 100.000%|██████████| 8518760/8518760 elapsed<00:01 remaining<00:00

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_hybrid_film_mlp_physics_all/model.joblib: 100.000%|██████████| 8518760/8518760 elapsed<00:01 remaining<00:00

Uploading model files (0 dirs, 4 files):  17%|█▋        | 1/6 [00:04<00:03,  1.41it/s]

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_hybrid_film_mlp_physics_all/pallas_pipeline.py: 0.000%|          | 0/20406 elapsed<00:00 remaining<?

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_hybrid_film_mlp_physics_all/pallas_pipeline.py: 100.000%|██████████| 20406/20406 elapsed<00:00 remaining<00:00

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_hybrid_film_mlp_physics_all/pallas_pipeline.py: 100.000%|██████████| 20406/20406 elapsed<00:00 remaining<00:00

Uploading model files (0 dirs, 5 files):  17%|█▋        | 1/6 [00:05<00:03,  1.41it/s]

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_hybrid_film_mlp_physics_all/moments_film_mlp.py: 0.000%|          | 0/13078 elapsed<00:00 remaining<?

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_hybrid_film_mlp_physics_all/moments_film_mlp.py: 100.000%|██████████| 13078/13078 elapsed<00:00 remaining<00:00

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_hybrid_film_mlp_physics_all/moments_film_mlp.py: 100.000%|██████████| 13078/13078 elapsed<00:00 remaining<00:00

Uploading model files (0 dirs, 6 files):  17%|█▋        | 1/6 [00:06<00:03,  1.41it/s]

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_hybrid_film_mlp_physics_all/requirements.txt: 0.000%|          | 0/122 elapsed<00:00 remaining<?

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_hybrid_film_mlp_physics_all/requirements.txt: 100.000%|██████████| 122/122 elapsed<00:00 remaining<00:00

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_hybrid_film_mlp_physics_all/requirements.txt: 100.000%|██████████| 122/122 elapsed<00:00 remaining<00:00

Uploading model files (0 dirs, 7 files):  17%|█▋        | 1/6 [00:07<00:03,  1.41it/s]

Uploading model files (0 dirs, 7 files):  33%|███▎      | 2/6 [00:07<00:16,  4.08s/it]

Uploading input_example and model_schema:  33%|███▎      | 2/6 [00:07<00:16,  4.08s/it]

Uploading /tmp/tmpw7qwqyx5/model_schema.json: 0.000%|          | 0/2455 elapsed<00:00 remaining<?

Uploading /tmp/tmpw7qwqyx5/model_schema.json: 100.000%|██████████| 2455/2455 elapsed<00:00 remaining<00:00

Uploading /tmp/tmpw7qwqyx5/model_schema.json: 100.000%|██████████| 2455/2455 elapsed<00:00 remaining<00:00

Uploading input_example and model_schema:  50%|█████     | 3/6 [00:07<00:07,  2.57s/it]

Registering model:  50%|█████     | 3/6 [00:07<00:07,  2.57s/it]

Registering model:  67%|██████▋   | 4/6 [00:08<00:03,  1.79s/it]

Waiting for model registration:  67%|██████▋   | 4/6 [00:08<00:03,  1.79s/it]

Waiting for model registration:  83%|████████▎ | 5/6 [00:13<00:03,  3.08s/it]

Model export complete:  83%|████████▎ | 5/6 [00:13<00:03,  3.08s/it]

Model export complete: 100%|██████████| 6/6 [00:13<00:00,  2.32s/it]

Model created, explore it at https://aissai26.hops.live:443/p/2170/models/m_moments_hybrid_film_mlp_physics_all/1
registered m_moments_hybrid_film_mlp_physics_all v1

  0%|          | 0/6 [00:00<?, ?it/s]

Creating model folder:   0%|          | 0/6 [00:00<?, ?it/s]

Creating model folder:  17%|█▋        | 1/6 [00:00<00:03,  1.45it/s]

Uploading model files:  17%|█▋        | 1/6 [00:00<00:03,  1.45it/s]

Uploading model files (0 dirs, 0 files):  17%|█▋        | 1/6 [00:00<00:03,  1.45it/s]

Moving model files from 'outputs/models/m_moments_hybrid_film_avg_centroids_all' to the model registry... This is the default behavior. Set keep_original_files=True to copy files instead.

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_hybrid_film_avg_centroids_all/model_meta.json: 0.000%|          | 0/7381 elapsed<00:00 remaining<?

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_hybrid_film_avg_centroids_all/model_meta.json: 100.000%|██████████| 7381/7381 elapsed<00:00 remaining<00:00

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_hybrid_film_avg_centroids_all/model_meta.json: 100.000%|██████████| 7381/7381 elapsed<00:00 remaining<00:00

Uploading model files (0 dirs, 1 files):  17%|█▋        | 1/6 [00:01<00:03,  1.45it/s]

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_hybrid_film_avg_centroids_all/physics_formulas.py: 0.000%|          | 0/20393 elapsed<00:00 remaining<?

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_hybrid_film_avg_centroids_all/physics_formulas.py: 100.000%|██████████| 20393/20393 elapsed<00:00 remaining<00:00

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_hybrid_film_avg_centroids_all/physics_formulas.py: 100.000%|██████████| 20393/20393 elapsed<00:00 remaining<00:00

Uploading model files (0 dirs, 2 files):  17%|█▋        | 1/6 [00:02<00:03,  1.45it/s]

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_hybrid_film_avg_centroids_all/pallas_score.py: 0.000%|          | 0/27702 elapsed<00:00 remaining<?

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_hybrid_film_avg_centroids_all/pallas_score.py: 100.000%|██████████| 27702/27702 elapsed<00:00 remaining<00:00

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_hybrid_film_avg_centroids_all/pallas_score.py: 100.000%|██████████| 27702/27702 elapsed<00:00 remaining<00:00

Uploading model files (0 dirs, 3 files):  17%|█▋        | 1/6 [00:03<00:03,  1.45it/s]

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_hybrid_film_avg_centroids_all/model.joblib: 0.000%|          | 0/12942305 elapsed<00:00 remaining<?

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_hybrid_film_avg_centroids_all/model.joblib: 18.981%|█▉        | 2456545/12942305 elapsed<00:00 remaining<00:03

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_hybrid_film_avg_centroids_all/model.joblib: 100.000%|██████████| 12942305/12942305 elapsed<00:01 remaining<00:00

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_hybrid_film_avg_centroids_all/model.joblib: 100.000%|██████████| 12942305/12942305 elapsed<00:01 remaining<00:00

Uploading model files (0 dirs, 4 files):  17%|█▋        | 1/6 [00:04<00:03,  1.45it/s]

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_hybrid_film_avg_centroids_all/pallas_pipeline.py: 0.000%|          | 0/20406 elapsed<00:00 remaining<?

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_hybrid_film_avg_centroids_all/pallas_pipeline.py: 100.000%|██████████| 20406/20406 elapsed<00:00 remaining<00:00

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_hybrid_film_avg_centroids_all/pallas_pipeline.py: 100.000%|██████████| 20406/20406 elapsed<00:00 remaining<00:00

Uploading model files (0 dirs, 5 files):  17%|█▋        | 1/6 [00:05<00:03,  1.45it/s]

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_hybrid_film_avg_centroids_all/moments_film_mlp.py: 0.000%|          | 0/13078 elapsed<00:00 remaining<?

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_hybrid_film_avg_centroids_all/moments_film_mlp.py: 100.000%|██████████| 13078/13078 elapsed<00:00 remaining<00:00

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_hybrid_film_avg_centroids_all/moments_film_mlp.py: 100.000%|██████████| 13078/13078 elapsed<00:00 remaining<00:00

Uploading model files (0 dirs, 6 files):  17%|█▋        | 1/6 [00:06<00:03,  1.45it/s]

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_hybrid_film_avg_centroids_all/requirements.txt: 0.000%|          | 0/122 elapsed<00:00 remaining<?

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_hybrid_film_avg_centroids_all/requirements.txt: 100.000%|██████████| 122/122 elapsed<00:00 remaining<00:00

Uploading /data/mykyta/HACKATHON/artifact-hackathon-2026_plasma_pirates/challenges/surrogate-models/outputs/models/m_moments_hybrid_film_avg_centroids_all/requirements.txt: 100.000%|██████████| 122/122 elapsed<00:00 remaining<00:00

Uploading model files (0 dirs, 7 files):  17%|█▋        | 1/6 [00:07<00:03,  1.45it/s]

Uploading model files (0 dirs, 7 files):  33%|███▎      | 2/6 [00:07<00:16,  4.06s/it]

Uploading input_example and model_schema:  33%|███▎      | 2/6 [00:07<00:16,  4.06s/it]

Uploading /tmp/tmpq4vpjwgg/model_schema.json: 0.000%|          | 0/2455 elapsed<00:00 remaining<?

Uploading /tmp/tmpq4vpjwgg/model_schema.json: 100.000%|██████████| 2455/2455 elapsed<00:00 remaining<00:00

Uploading /tmp/tmpq4vpjwgg/model_schema.json: 100.000%|██████████| 2455/2455 elapsed<00:00 remaining<00:00

Uploading input_example and model_schema:  50%|█████     | 3/6 [00:07<00:07,  2.57s/it]

Registering model:  50%|█████     | 3/6 [00:07<00:07,  2.57s/it]

Registering model:  67%|██████▋   | 4/6 [00:08<00:03,  1.78s/it]

Waiting for model registration:  67%|██████▋   | 4/6 [00:08<00:03,  1.78s/it]

Waiting for model registration:  83%|████████▎ | 5/6 [00:13<00:03,  3.07s/it]

Model export complete:  83%|████████▎ | 5/6 [00:13<00:03,  3.07s/it]

Model export complete: 100%|██████████| 6/6 [00:13<00:00,  2.31s/it]

Model created, explore it at https://aissai26.hops.live:443/p/2170/models/m_moments_hybrid_film_avg_centroids_all/1
registered m_moments_hybrid_film_avg_centroids_all v1

## 5. Load each back from the registry, write the submissions

One folder per model under `submissions/moments/`, each with `submission_moments.csv` (3,213 rows of
`test_moments_planes.parquet`).

In [6]:
to_submit = pd.read_parquet(pp.DATA_DIR / "test_moments_planes.parquet")
case = SimpleNamespace(targets=TARGETS, ids=["config", "plane_mm"])
listing = {}
for name, m in models_all.items():
    NAME_ALL = f"{OWNER}_{CASE}_{name}_all"
    if registered[name] is not None:
        version = registered[name].version
        loaded, _ = pp.load_registered_model(project, NAME_ALL, version, "team_models")
    else:
        version, loaded = 0, m
    pred = loaded.predict(to_submit)
    assert np.allclose(pred.to_numpy(), m.predict(to_submit).to_numpy())        # registry copy = this one
    submission = pd.concat([to_submit[["config", "plane_mm"]].reset_index(drop=True), pred], axis=1)
    path = pp.write_submission(case, submission, to_submit, Path("submissions") / CASE / f"{NAME_ALL}_v{version}" / "submission_moments.csv")
    listing[name] = {"test R2": round(table.loc[name, "mean"], 4), "model": f"{NAME_ALL} v{version}", "file": str(path)}
print(f"--- done {(time.time() - started) / 60:.1f} min")
pd.DataFrame(listing).T

Downloading: 0.000%|          | 0/122 elapsed<00:00 remaining<?

Downloading: 100.000%|██████████| 122/122 elapsed<00:00 remaining<00:00

Downloading: 0.000%|          | 0/20393 elapsed<00:00 remaining<?

Downloading: 100.000%|██████████| 20393/20393 elapsed<00:00 remaining<00:00

Downloading: 0.000%|          | 0/27702 elapsed<00:00 remaining<?

Downloading: 100.000%|██████████| 27702/27702 elapsed<00:00 remaining<00:00

Downloading: 100.000%|██████████| 27702/27702 elapsed<00:00 remaining<00:00

Downloading: 0.000%|          | 0/20406 elapsed<00:00 remaining<?

Downloading: 100.000%|██████████| 20406/20406 elapsed<00:00 remaining<00:00

Downloading: 0.000%|          | 0/13078 elapsed<00:00 remaining<?

Downloading: 100.000%|██████████| 13078/13078 elapsed<00:00 remaining<00:00

Downloading: 0.000%|          | 0/7337 elapsed<00:00 remaining<?

Downloading: 100.000%|██████████| 7337/7337 elapsed<00:00 remaining<00:00

Downloading: 0.000%|          | 0/4074302 elapsed<00:00 remaining<?

Downloading: 1.058%|          | 43094/4074302 elapsed<00:00 remaining<00:12

Downloading: 2.384%|▏         | 97122/4074302 elapsed<00:00 remaining<00:10

Downloading: 3.745%|▎         | 152602/4074302 elapsed<00:00 remaining<00:09

Downloading: 5.319%|▌         | 216730/4074302 elapsed<00:00 remaining<00:08

Downloading: 6.927%|▋         | 282210/4074302 elapsed<00:00 remaining<00:08

Downloading: 8.735%|▊         | 355874/4074302 elapsed<00:00 remaining<00:07

Downloading: 10.682%|█         | 435226/4074302 elapsed<00:00 remaining<00:06

Downloading: 12.792%|█▎        | 521170/4074302 elapsed<00:01 remaining<00:06

Downloading: 15.121%|█▌        | 616070/4074302 elapsed<00:01 remaining<00:05

Downloading: 17.531%|█▊        | 714286/4074302 elapsed<00:01 remaining<00:05

Downloading: 19.985%|█▉        | 814258/4074302 elapsed<00:01 remaining<00:04

Downloading: 22.673%|██▎       | 923762/4074302 elapsed<00:01 remaining<00:04

Downloading: 25.485%|██▌       | 1038354/4074302 elapsed<00:01 remaining<00:03

Downloading: 27.494%|██▋       | 1120202/4074302 elapsed<00:01 remaining<00:04

Downloading: 30.407%|███       | 1238882/4074302 elapsed<00:01 remaining<00:03

Downloading: 32.360%|███▏      | 1318434/4074302 elapsed<00:02 remaining<00:04

Downloading: 34.670%|███▍      | 1412562/4074302 elapsed<00:02 remaining<00:03

Downloading: 36.371%|███▋      | 1481874/4074302 elapsed<00:02 remaining<00:04

Downloading: 38.179%|███▊      | 1555538/4074302 elapsed<00:02 remaining<00:04

Downloading: 40.208%|████      | 1638210/4074302 elapsed<00:02 remaining<00:03

Downloading: 42.216%|████▏     | 1720002/4074302 elapsed<00:02 remaining<00:03

Downloading: 44.426%|████▍     | 1810034/4074302 elapsed<00:02 remaining<00:03

Downloading: 46.896%|████▋     | 1910682/4074302 elapsed<00:03 remaining<00:03

Downloading: 49.366%|████▉     | 2011330/4074302 elapsed<00:03 remaining<00:02

Downloading: 52.034%|█████▏    | 2120006/4074302 elapsed<00:03 remaining<00:02

Downloading: 54.830%|█████▍    | 2233922/4074302 elapsed<00:03 remaining<00:02

Downloading: 57.782%|█████▊    | 2354202/4074302 elapsed<00:03 remaining<00:02

Downloading: 60.939%|██████    | 2482826/4074302 elapsed<00:03 remaining<00:01

Downloading: 64.153%|██████▍   | 2613786/4074302 elapsed<00:03 remaining<00:01

Downloading: 66.418%|██████▋   | 2706090/4074302 elapsed<00:03 remaining<00:01

Downloading: 69.934%|██████▉   | 2849322/4074302 elapsed<00:04 remaining<00:01

Downloading: 72.565%|███████▎  | 2956498/4074302 elapsed<00:04 remaining<00:01

Downloading: 75.377%|███████▌  | 3071082/4074302 elapsed<00:04 remaining<00:01

Downloading: 78.290%|███████▊  | 3189762/4074302 elapsed<00:04 remaining<00:01

Downloading: 81.224%|████████  | 3309310/4074302 elapsed<00:04 remaining<00:00

Downloading: 84.328%|████████▍ | 3435762/4074302 elapsed<00:04 remaining<00:00

Downloading: 87.570%|████████▊ | 3567850/4074302 elapsed<00:04 remaining<00:00

Downloading: 91.016%|█████████ | 3708286/4074302 elapsed<00:05 remaining<00:00

Downloading: 94.604%|█████████▍| 3854466/4074302 elapsed<00:05 remaining<00:00

Downloading: 98.439%|█████████▊| 4010698/4074302 elapsed<00:05 remaining<00:00

Downloading: 100.000%|██████████| 4074302/4074302 elapsed<00:05 remaining<00:00

Downloading: 0.000%|          | 0/122 elapsed<00:00 remaining<?

Downloading: 100.000%|██████████| 122/122 elapsed<00:00 remaining<00:00

Downloading: 0.000%|          | 0/20393 elapsed<00:00 remaining<?

Downloading: 100.000%|██████████| 20393/20393 elapsed<00:00 remaining<00:00

Downloading: 0.000%|          | 0/27702 elapsed<00:00 remaining<?

Downloading: 100.000%|██████████| 27702/27702 elapsed<00:00 remaining<00:00

Downloading: 0.000%|          | 0/20406 elapsed<00:00 remaining<?

Downloading: 100.000%|██████████| 20406/20406 elapsed<00:00 remaining<00:00

Downloading: 0.000%|          | 0/13078 elapsed<00:00 remaining<?

Downloading: 100.000%|██████████| 13078/13078 elapsed<00:00 remaining<00:00

Downloading: 0.000%|          | 0/7353 elapsed<00:00 remaining<?

Downloading: 100.000%|██████████| 7353/7353 elapsed<00:00 remaining<00:00

Downloading: 0.000%|          | 0/4094858 elapsed<00:00 remaining<?

Downloading: 3.899%|▍         | 159678/4094858 elapsed<00:00 remaining<00:03

Downloading: 8.143%|▊         | 333434/4094858 elapsed<00:00 remaining<00:02

Downloading: 12.161%|█▏        | 497974/4094858 elapsed<00:00 remaining<00:02

Downloading: 16.544%|█▋        | 677458/4094858 elapsed<00:00 remaining<00:02

Downloading: 20.428%|██        | 836510/4094858 elapsed<00:00 remaining<00:02

Downloading: 23.632%|██▎       | 967680/4094858 elapsed<00:00 remaining<00:02

Downloading: 27.008%|██▋       | 1105920/4094858 elapsed<00:00 remaining<00:02

Downloading: 30.606%|███       | 1253262/4094858 elapsed<00:01 remaining<00:02

Downloading: 34.265%|███▍      | 1403122/4094858 elapsed<00:01 remaining<00:02

Downloading: 38.090%|███▊      | 1559718/4094858 elapsed<00:01 remaining<00:02

Downloading: 42.051%|████▏     | 1721930/4094858 elapsed<00:01 remaining<00:02

Downloading: 45.987%|████▌     | 1883122/4094858 elapsed<00:01 remaining<00:01

Downloading: 49.403%|████▉     | 2022974/4094858 elapsed<00:01 remaining<00:01

Downloading: 52.512%|█████▎    | 2150302/4094858 elapsed<00:01 remaining<00:01

Downloading: 55.530%|█████▌    | 2273890/4094858 elapsed<00:01 remaining<00:01

Downloading: 58.682%|█████▊    | 2402946/4094858 elapsed<00:02 remaining<00:01

Downloading: 62.015%|██████▏   | 2539438/4094858 elapsed<00:02 remaining<00:01

Downloading: 65.500%|██████▌   | 2682114/4094858 elapsed<00:02 remaining<00:01

Downloading: 69.183%|██████▉   | 2832950/4094858 elapsed<00:02 remaining<00:01

Downloading: 73.017%|███████▎  | 2989958/4094858 elapsed<00:02 remaining<00:00

Downloading: 76.953%|███████▋  | 3151106/4094858 elapsed<00:02 remaining<00:00

Downloading: 81.021%|████████  | 3317678/4094858 elapsed<00:02 remaining<00:00

Downloading: 85.397%|████████▌ | 3496870/4094858 elapsed<00:03 remaining<00:00

Downloading: 89.773%|████████▉ | 3676070/4094858 elapsed<00:03 remaining<00:00

Downloading: 94.176%|█████████▍| 3856378/4094858 elapsed<00:03 remaining<00:00

Downloading: 99.001%|█████████▉| 4053946/4094858 elapsed<00:03 remaining<00:00

Downloading: 100.000%|██████████| 4094858/4094858 elapsed<00:03 remaining<00:00

Downloading: 0.000%|          | 0/122 elapsed<00:00 remaining<?

Downloading: 100.000%|██████████| 122/122 elapsed<00:00 remaining<00:00

Downloading: 0.000%|          | 0/20393 elapsed<00:00 remaining<?

Downloading: 100.000%|██████████| 20393/20393 elapsed<00:00 remaining<00:00

Downloading: 0.000%|          | 0/27702 elapsed<00:00 remaining<?

Downloading: 100.000%|██████████| 27702/27702 elapsed<00:00 remaining<00:00

Downloading: 0.000%|          | 0/20406 elapsed<00:00 remaining<?

Downloading: 100.000%|██████████| 20406/20406 elapsed<00:00 remaining<00:00

Downloading: 0.000%|          | 0/13078 elapsed<00:00 remaining<?

Downloading: 100.000%|██████████| 13078/13078 elapsed<00:00 remaining<00:00

Downloading: 0.000%|          | 0/7369 elapsed<00:00 remaining<?

Downloading: 100.000%|██████████| 7369/7369 elapsed<00:00 remaining<00:00

Downloading: 0.000%|          | 0/4424774 elapsed<00:00 remaining<?

Downloading: 4.056%|▍         | 179478/4424774 elapsed<00:00 remaining<00:03

Downloading: 8.796%|▉         | 389222/4424774 elapsed<00:00 remaining<00:02

Downloading: 13.678%|█▎        | 605234/4424774 elapsed<00:00 remaining<00:02

Downloading: 18.680%|█▊        | 826546/4424774 elapsed<00:00 remaining<00:02

Downloading: 23.837%|██▍       | 1054714/4424774 elapsed<00:00 remaining<00:02

Downloading: 28.694%|██▊       | 1269630/4424774 elapsed<00:00 remaining<00:02

Downloading: 34.504%|███▍      | 1526710/4424774 elapsed<00:00 remaining<00:01

Downloading: 38.274%|███▊      | 1693534/4424774 elapsed<00:01 remaining<00:01

Downloading: 42.525%|████▎     | 1881638/4424774 elapsed<00:01 remaining<00:01

Downloading: 46.067%|████▌     | 2038342/4424774 elapsed<00:01 remaining<00:01

Downloading: 49.177%|████▉     | 2175970/4424774 elapsed<00:01 remaining<00:01

Downloading: 52.146%|█████▏    | 2307322/4424774 elapsed<00:01 remaining<00:01

Downloading: 55.179%|█████▌    | 2441526/4424774 elapsed<00:01 remaining<00:01

Downloading: 57.970%|█████▊    | 2565022/4424774 elapsed<00:01 remaining<00:01

Downloading: 61.030%|██████    | 2700438/4424774 elapsed<00:01 remaining<00:01

Downloading: 64.056%|██████▍   | 2834318/4424774 elapsed<00:02 remaining<00:01

Downloading: 67.388%|██████▋   | 2981774/4424774 elapsed<00:02 remaining<00:01

Downloading: 70.697%|███████   | 3128166/4424774 elapsed<00:02 remaining<00:01

Downloading: 74.145%|███████▍  | 3280750/4424774 elapsed<00:02 remaining<00:00

Downloading: 77.564%|███████▊  | 3432042/4424774 elapsed<00:02 remaining<00:00

Downloading: 80.698%|████████  | 3570682/4424774 elapsed<00:02 remaining<00:00

Downloading: 84.930%|████████▍ | 3757950/4424774 elapsed<00:02 remaining<00:00

Downloading: 87.917%|████████▊ | 3890146/4424774 elapsed<00:02 remaining<00:00

Downloading: 90.926%|█████████ | 4023266/4424774 elapsed<00:03 remaining<00:00

Downloading: 93.701%|█████████▎| 4146042/4424774 elapsed<00:03 remaining<00:00

Downloading: 96.198%|█████████▌| 4256538/4424774 elapsed<00:03 remaining<00:00

Downloading: 98.510%|█████████▊| 4358850/4424774 elapsed<00:03 remaining<00:00

Downloading: 100.000%|██████████| 4424774/4424774 elapsed<00:03 remaining<00:00

Downloading: 0.000%|          | 0/122 elapsed<00:00 remaining<?

Downloading: 100.000%|██████████| 122/122 elapsed<00:00 remaining<00:00

Downloading: 0.000%|          | 0/20393 elapsed<00:00 remaining<?

Downloading: 100.000%|██████████| 20393/20393 elapsed<00:00 remaining<00:00

Downloading: 0.000%|          | 0/27702 elapsed<00:00 remaining<?

Downloading: 100.000%|██████████| 27702/27702 elapsed<00:00 remaining<00:00

Downloading: 0.000%|          | 0/20406 elapsed<00:00 remaining<?

Downloading: 100.000%|██████████| 20406/20406 elapsed<00:00 remaining<00:00

Downloading: 0.000%|          | 0/13078 elapsed<00:00 remaining<?

Downloading: 100.000%|██████████| 13078/13078 elapsed<00:00 remaining<00:00

Downloading: 0.000%|          | 0/7376 elapsed<00:00 remaining<?

Downloading: 100.000%|██████████| 7376/7376 elapsed<00:00 remaining<00:00

Downloading: 100.000%|██████████| 7376/7376 elapsed<00:00 remaining<00:00

Downloading: 0.000%|          | 0/8518760 elapsed<00:00 remaining<?

Downloading: 0.950%|          | 80962/8518760 elapsed<00:00 remaining<00:13

Downloading: 1.983%|▏         | 168918/8518760 elapsed<00:00 remaining<00:12

Downloading: 3.040%|▎         | 258946/8518760 elapsed<00:00 remaining<00:12

Downloading: 4.241%|▍         | 361258/8518760 elapsed<00:00 remaining<00:11

Downloading: 5.459%|▌         | 465066/8518760 elapsed<00:00 remaining<00:10

Downloading: 6.804%|▋         | 579658/8518760 elapsed<00:00 remaining<00:10

Downloading: 8.193%|▊         | 697922/8518760 elapsed<00:00 remaining<00:09

Downloading: 9.612%|▉         | 818794/8518760 elapsed<00:01 remaining<00:09

Downloading: 11.110%|█         | 946418/8518760 elapsed<00:01 remaining<00:08

Downloading: 12.729%|█▎        | 1084394/8518760 elapsed<00:01 remaining<00:07

Downloading: 14.408%|█▍        | 1227386/8518760 elapsed<00:01 remaining<00:07

Downloading: 16.120%|█▌        | 1373184/8518760 elapsed<00:01 remaining<00:06

Downloading: 17.341%|█▋        | 1477218/8518760 elapsed<00:01 remaining<00:07

Downloading: 19.197%|█▉        | 1635322/8518760 elapsed<00:01 remaining<00:06

Downloading: 20.638%|██        | 1758090/8518760 elapsed<00:01 remaining<00:06

Downloading: 22.093%|██▏       | 1882090/8518760 elapsed<00:02 remaining<00:06

Downloading: 23.632%|██▎       | 2013114/8518760 elapsed<00:02 remaining<00:06

Downloading: 24.822%|██▍       | 2114554/8518760 elapsed<00:02 remaining<00:07

Downloading: 26.733%|██▋       | 2277294/8518760 elapsed<00:02 remaining<00:06

Downloading: 27.919%|██▊       | 2378322/8518760 elapsed<00:02 remaining<00:06

Downloading: 28.993%|██▉       | 2469858/8518760 elapsed<00:02 remaining<00:07

Downloading: 29.930%|██▉       | 2549654/8518760 elapsed<00:02 remaining<00:08

Downloading: 30.917%|███       | 2633714/8518760 elapsed<00:03 remaining<00:08

Downloading: 31.877%|███▏      | 2715522/8518760 elapsed<00:03 remaining<00:08

Downloading: 33.024%|███▎      | 2813270/8518760 elapsed<00:03 remaining<00:08

Downloading: 34.221%|███▍      | 2915230/8518760 elapsed<00:03 remaining<00:07

Downloading: 35.490%|███▌      | 3023314/8518760 elapsed<00:03 remaining<00:07

Downloading: 36.787%|███▋      | 3133810/8518760 elapsed<00:03 remaining<00:06

Downloading: 38.180%|███▊      | 3252498/8518760 elapsed<00:03 remaining<00:06

Downloading: 39.659%|███▉      | 3378482/8518760 elapsed<00:04 remaining<00:05

Downloading: 41.170%|████      | 3507170/8518760 elapsed<00:04 remaining<00:05

Downloading: 42.749%|████▎     | 3641662/8518760 elapsed<00:04 remaining<00:05

Downloading: 44.461%|████▍     | 3787514/8518760 elapsed<00:04 remaining<00:04

Downloading: 46.231%|████▌     | 3938290/8518760 elapsed<00:04 remaining<00:04

Downloading: 48.077%|████▊     | 4095542/8518760 elapsed<00:04 remaining<00:04

Downloading: 49.992%|████▉     | 4258690/8518760 elapsed<00:04 remaining<00:03

Downloading: 52.010%|█████▏    | 4430578/8518760 elapsed<00:04 remaining<00:03

Downloading: 54.075%|█████▍    | 4606554/8518760 elapsed<00:05 remaining<00:03

Downloading: 56.189%|█████▌    | 4786618/8518760 elapsed<00:05 remaining<00:02

Downloading: 58.351%|█████▊    | 4970778/8518760 elapsed<00:05 remaining<00:02

Downloading: 60.609%|██████    | 5163122/8518760 elapsed<00:05 remaining<00:02

Downloading: 62.963%|██████▎   | 5363658/8518760 elapsed<00:05 remaining<00:02

Downloading: 65.413%|██████▌   | 5572370/8518760 elapsed<00:05 remaining<00:02

Downloading: 67.911%|██████▊   | 5785178/8518760 elapsed<00:05 remaining<00:01

Downloading: 70.505%|███████   | 6006170/8518760 elapsed<00:06 remaining<00:01

Downloading: 73.147%|███████▎  | 6231250/8518760 elapsed<00:06 remaining<00:01

Downloading: 75.886%|███████▌  | 6464522/8518760 elapsed<00:06 remaining<00:01

Downloading: 78.048%|███████▊  | 6648682/8518760 elapsed<00:06 remaining<00:01

Downloading: 80.738%|████████  | 6877858/8518760 elapsed<00:06 remaining<00:00

Downloading: 82.756%|████████▎ | 7049746/8518760 elapsed<00:06 remaining<00:00

Downloading: 84.725%|████████▍ | 7217530/8518760 elapsed<00:06 remaining<00:00

Downloading: 86.599%|████████▋ | 7377138/8518760 elapsed<00:06 remaining<00:00

Downloading: 88.664%|████████▊ | 7553114/8518760 elapsed<00:06 remaining<00:00

Downloading: 90.490%|█████████ | 7708626/8518760 elapsed<00:07 remaining<00:00

Downloading: 92.604%|█████████▎| 7888698/8518760 elapsed<00:07 remaining<00:00

Downloading: 94.477%|█████████▍| 8048298/8518760 elapsed<00:07 remaining<00:00

Downloading: 96.735%|█████████▋| 8240642/8518760 elapsed<00:07 remaining<00:00

Downloading: 98.657%|█████████▊| 8404346/8518760 elapsed<00:07 remaining<00:00

Downloading: 100.000%|██████████| 8518760/8518760 elapsed<00:07 remaining<00:00

Downloading: 0.000%|          | 0/122 elapsed<00:00 remaining<?

Downloading: 100.000%|██████████| 122/122 elapsed<00:00 remaining<00:00

Downloading: 0.000%|          | 0/20393 elapsed<00:00 remaining<?

Downloading: 100.000%|██████████| 20393/20393 elapsed<00:00 remaining<00:00

Downloading: 0.000%|          | 0/27702 elapsed<00:00 remaining<?

Downloading: 100.000%|██████████| 27702/27702 elapsed<00:00 remaining<00:00

Downloading: 0.000%|          | 0/20406 elapsed<00:00 remaining<?

Downloading: 100.000%|██████████| 20406/20406 elapsed<00:00 remaining<00:00

Downloading: 0.000%|          | 0/13078 elapsed<00:00 remaining<?

Downloading: 100.000%|██████████| 13078/13078 elapsed<00:00 remaining<00:00

Downloading: 0.000%|          | 0/7381 elapsed<00:00 remaining<?

Downloading: 100.000%|██████████| 7381/7381 elapsed<00:00 remaining<00:00

Downloading: 0.000%|          | 0/12942305 elapsed<00:00 remaining<?

Downloading: 1.488%|▏         | 192542/12942305 elapsed<00:00 remaining<00:08

Downloading: 3.256%|▎         | 421398/12942305 elapsed<00:00 remaining<00:07

Downloading: 5.060%|▌         | 654930/12942305 elapsed<00:00 remaining<00:07

Downloading: 6.888%|▋         | 891490/12942305 elapsed<00:00 remaining<00:06

Downloading: 8.798%|▉         | 1138606/12942305 elapsed<00:00 remaining<00:06

Downloading: 10.768%|█         | 1393590/12942305 elapsed<00:00 remaining<00:06

Downloading: 12.751%|█▎        | 1650290/12942305 elapsed<00:00 remaining<00:06

Downloading: 14.771%|█▍        | 1911686/12942305 elapsed<00:01 remaining<00:05

Downloading: 16.881%|█▋        | 2184754/12942305 elapsed<00:01 remaining<00:05

Downloading: 19.037%|█▉        | 2463866/12942305 elapsed<00:01 remaining<00:05

Downloading: 21.219%|██        | 2746250/12942305 elapsed<00:01 remaining<00:04

Downloading: 23.516%|██▎       | 3043570/12942305 elapsed<00:01 remaining<00:04

Downloading: 25.802%|██▌       | 3339418/12942305 elapsed<00:01 remaining<00:04

Downloading: 28.141%|██▊       | 3642114/12942305 elapsed<00:01 remaining<00:04

Downloading: 30.568%|███       | 3956194/12942305 elapsed<00:01 remaining<00:03

Downloading: 33.023%|███▎      | 4273994/12942305 elapsed<00:02 remaining<00:03

Downloading: 35.490%|███▌      | 4593202/12942305 elapsed<00:02 remaining<00:03

Downloading: 37.324%|███▋      | 4830562/12942305 elapsed<00:02 remaining<00:03

Downloading: 40.075%|████      | 5186610/12942305 elapsed<00:02 remaining<00:03

Downloading: 41.972%|████▏     | 5432154/12942305 elapsed<00:02 remaining<00:03

Downloading: 43.933%|████▍     | 5685890/12942305 elapsed<00:02 remaining<00:03

Downloading: 45.925%|████▌     | 5943714/12942305 elapsed<00:02 remaining<00:03

Downloading: 48.012%|████▊     | 6213810/12942305 elapsed<00:03 remaining<00:03

Downloading: 50.162%|█████     | 6492098/12942305 elapsed<00:03 remaining<00:03

Downloading: 52.344%|█████▏    | 6774474/12942305 elapsed<00:03 remaining<00:02

Downloading: 54.589%|█████▍    | 7065042/12942305 elapsed<00:03 remaining<00:02

Downloading: 56.865%|█████▋    | 7359698/12942305 elapsed<00:03 remaining<00:02

Downloading: 59.205%|█████▉    | 7662538/12942305 elapsed<00:03 remaining<00:02

Downloading: 61.545%|██████▏   | 7965378/12942305 elapsed<00:03 remaining<00:02

Downloading: 63.948%|██████▍   | 8276402/12942305 elapsed<00:03 remaining<00:02

Downloading: 66.415%|██████▋   | 8595618/12942305 elapsed<00:04 remaining<00:01

Downloading: 68.881%|██████▉   | 8914826/12942305 elapsed<00:04 remaining<00:01

Downloading: 71.348%|███████▏  | 9234042/12942305 elapsed<00:04 remaining<00:01

Downloading: 73.846%|███████▍  | 9557338/12942305 elapsed<00:04 remaining<00:01

Downloading: 76.375%|███████▋  | 9884738/12942305 elapsed<00:04 remaining<00:01

Downloading: 78.937%|███████▉  | 10216226/12942305 elapsed<00:04 remaining<00:01

Downloading: 81.561%|████████▏ | 10555898/12942305 elapsed<00:04 remaining<00:00

Downloading: 84.217%|████████▍ | 10899666/12942305 elapsed<00:04 remaining<00:00

Downloading: 86.937%|████████▋ | 11251618/12942305 elapsed<00:05 remaining<00:00

Downloading: 89.719%|████████▉ | 11611754/12942305 elapsed<00:05 remaining<00:00

Downloading: 92.534%|█████████▎| 11975978/12942305 elapsed<00:05 remaining<00:00

Downloading: 95.095%|█████████▌| 12307466/12942305 elapsed<00:05 remaining<00:00

Downloading: 97.119%|█████████▋| 12569386/12942305 elapsed<00:05 remaining<00:00

Downloading: 99.237%|█████████▉| 12843578/12942305 elapsed<00:05 remaining<00:00

Downloading: 100.000%|██████████| 12942305/12942305 elapsed<00:05 remaining<00:00

--- done 63.4 min

,test R2,model,file
mlp,0.8129,m_moments_mlp_all v1,submissions/moments/m_moments_mlp_all_v1/submi...
mlp_physics,0.8172,m_moments_mlp_physics_all v1,submissions/moments/m_moments_mlp_physics_all_...
film_centroid_term,0.8153,m_moments_film_centroid_term_all v1,submissions/moments/m_moments_film_centroid_te...
hybrid_film_mlp_physics,0.8254,m_moments_hybrid_film_mlp_physics_all v1,submissions/moments/m_moments_hybrid_film_mlp_...
hybrid_film_avg_centroids,0.8263,m_moments_hybrid_film_avg_centroids_all v1,submissions/moments/m_moments_hybrid_film_avg_...