# dd.list のデータを cycle_id ごとの DataFrame として保存

作業ディレクトリの `dd_by_cycle/` に、サイクルごとの pandas DataFrame を `<cycle_id>.pkl` として保存しています。
1行は元データの1つのPV取得に対応し、`data_array` 列には間引きなしの波形配列が入ります。HBL・MBL・BCMなど全グループの元の列を保持し、同じ取得データが複数のアーカイブにある場合もすべて残します。

元データは約31GBあるため、必要なサイクルだけ読み込みます。`cycle_summary.csv` は全サイクルの件数一覧です。

In [1]:
from pathlib import Path
import pandas as pd
from dd_cycles import CycleDataFrames

WORK_DIR = Path.cwd()
DATA_DIR = WORK_DIR / "dd_by_cycle"
dfs_by_cycle = CycleDataFrames(DATA_DIR)
cycle_summary = dfs_by_cycle.summary
print(f"保存先: {DATA_DIR}")
print(f"{len(dfs_by_cycle):,} cycles / {cycle_summary['rows'].sum():,} rows")
display(cycle_summary.head(10))

保存先: /lustre/work/pdl18409/shared/Anomaly_Hunter/dd_by_cycle
737 cycles / 218,533 rows

      cycle_id  ...             file
0  15643300178  ...  15643300178.pkl
1  15643300192  ...  15643300192.pkl
2  15643300206  ...  15643300206.pkl
3  15643300220  ...  15643300220.pkl
4  15643300234  ...  15643300234.pkl
5  15643300248  ...  15643300248.pkl
6  15643300262  ...  15643300262.pkl
7  15643300276  ...  15643300276.pkl
8  15643300290  ...  15643300290.pkl
9  16096681837  ...  16096681837.pkl

[10 rows x 8 columns]

## cycle_id を指定してDataFrameを取得

辞書と同様に `dfs_by_cycle[cycle_id]` でアクセスできます。アクセスするたびに1つのDataFrameを読み込みます。

In [2]:
cycle_id = 15643300178  # この値を見たいcycle_idに変更
cycle_df = dfs_by_cycle[cycle_id]
print(type(cycle_df), cycle_df.shape)
display(cycle_df.head())

<class 'pandas.core.frame.DataFrame'> (48, 34)

      cycle_id  ... source_row
0  15643300178  ...         64
1  15643300178  ...         65
2  15643300178  ...         66
3  15643300178  ...         67
4  15643300178  ...         68

[5 rows x 34 columns]

## pandasだけで直接読み込む場合

In [3]:
cycle_df = pd.read_pickle(DATA_DIR / f"{cycle_id}.pkl")
display(cycle_df[["cycle_id", "cycle_ts", "pv", "data_ts", "array_size", "source_archive"]].head())

      cycle_id  ...                                     source_archive
0  15643300178  ...  /lustre/work/pdl18409/shared/data/anomaly-dete...
1  15643300178  ...  /lustre/work/pdl18409/shared/data/anomaly-dete...
2  15643300178  ...  /lustre/work/pdl18409/shared/data/anomaly-dete...
3  15643300178  ...  /lustre/work/pdl18409/shared/data/anomaly-dete...
4  15643300178  ...  /lustre/work/pdl18409/shared/data/anomaly-dete...

[5 rows x 6 columns]

## PVごとの波形を取り出す

`data_array` は NumPy 配列です。配列の長さはPVによって異なります。`source_archive` と `source_parquet` が元ファイルを示し、`source_row` は元Parquet内の0始まりの行番号、`source_list_line` は `dd.list` の行番号です。

In [4]:
target_pv = cycle_df["pv"].iloc[0]
pv_df = cycle_df.loc[cycle_df["pv"].eq(target_pv)].reset_index(drop=True)
waveform = pv_df["data_array"].iloc[0]
print("PV:", target_pv)
print("波形のサンプル数:", len(waveform) if waveform is not None else 0)
display(pv_df[["cycle_id", "pv", "data_array", "source_parquet", "source_row"]])

PV: HBL-010RFC:RFS-DIG-101:Dwn0-Cmp0SDS-DODData
波形のサンプル数: 35221

      cycle_id  ... source_row
0  15643300178  ...         64
1  15643300178  ...         64

[2 rows x 5 columns]

## 別のdd.listから新しく作成する場合

`pandas` と `pyarrow` が必要です。以下は既存の保存先を上書きせず、新しいフォルダにDataFrameを作成します。

In [5]:
# from dd_cycles import build_cycle_dataframes
# build_cycle_dataframes("dd.list", "dd_by_cycle_new")